### ISSUE TITLE
Error when opening DocType Configuration Item

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#11]
![grafik](https://user-images.githubusercontent.com/22279621/67087340-022d5780-f1a3-11e9-95de-b5c632be7b0e.png)

**Comment by joelios** [comment]
**Cause**:
The dashboard of doctype "Configuration Item" tries to find all related tasks (doctype Task). I guess you had (when you were still on V11) a customfield "Configuration Item" in the doctype "Task". this seems to be missing, which is why the sql query from the "Configuration Item" dashboard causes this error.

**Solution**:
Recreate the custom link-field "Configuration Item" in the doctype "Task".

**Comment by wojosc** [comment]
We also have the "IT Management Table" in the DocType Task. This is still implemented in v12 also. In v11 we used to have another table called "Task Checklist" this has been deprecated and not user anymore. Is it maybe this?

**Comment by joelios** [comment]
The error is clearly caused by the dashboard of the doctype "Configuration Item". I had the same error earlier on my test system too, since I set this up anew and therefore of course had no custom link field to doctype "Configuration Item" on the doctype "Task". I suspect during the update from V11 to V12 this customization was lost.

**Comment by joelios** [comment]
To prevent this error from occurring again, I recommend exporting the customizations to the "IT Management"-App. Then this error does not occur again in a future update or during a new installation.

**Comment by barredterra** [comment]
A solution would be to add `'Task': 'dynamic_name'` under `non_standard_fieldnames` in `configuration_item_dashboard.py`.

**Comment by joelios** [comment]
solved with `'Task': 'dynamic_name'` under `non_standard_fieldnames` in `configuration_item_dashboard.py`

**Comment by wojosc** [comment]
![grafik](https://user-images.githubusercontent.com/22279621/68103740-542ae880-fed8-11e9-9c58-0d2e59050ccf.png)

Bitte noch einmal drüber schauen und das beheben. Danke.

**Comment by wojosc** [comment]
https://github.com/tueit/it_management/tree/master/it_management/it_management/doctype/configuration_item

**Comment by lasalesi** [comment]
Hotfix PR #31
