### ISSUE TITLE
add dashboard

### ISSUE THREAD

**Issue by wojosc** [tueit/it_management#146]
In Contact we can add a dashboard in which we have links to

- [ ] Lead, Opportunity, 

- [ ] Quotation, 

- [ ] Sales Order, 

- [ ] Sales Invoice, 

- [ ] Maintanence Visit and 

- [ ] Issue.

All these Standard Doctype already have the field contact.

Further we can add IT Management links to

- [ ] Configuration Item and

- [ ] User Account

The purpose is ease of use when for example a person calls and you need to find open issues quickly

**Comment by canlann** [comment]
In Contact we can add a dashboard in which we have links to

- [ ] Lead (no contact in lead)

- [ ] Opportunity (no contact in opportunity)

- [x] Quotation,

- [x] Sales Order,

- [x] Sales Invoice,

- [x] Maintanence Visit and

- [x] Issue.

All these Standard Doctype already have the field contact.

Further we can add IT Management links to

- [ ] Configuration Item (Not possible since MultiSelect Fields... Frappe Bug) https://github.com/frappe/frappe/issues/11857

- [x] User Account

**Comment by canlann** [comment]
@wojosc FYI
